# Generated by Django 3.1.7 on 2022-07-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('url', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='videoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageTitle', models.CharField(max_length=200)),
                ('imageURL', models.TextField(blank=True, null=True)),
                ('imageDescription', models.TextField(blank=True, null=True)),
                ('slugImage', models.CharField(blank=True, max_length=1000, null=True)),
                ('slugImageDetail', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('imageKeyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchIMG.post')),
            ],
        ),
    ]
