# Generated by Django 4.0.6 on 2022-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchIMG', '0002_auto_20220723_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='imageURLHD',
            field=models.TextField(blank=True, null=True),
        ),
    ]
